### ISSUE TITLE
Feedback on page: /configuration/customers/reward-points.html

### ISSUE THREAD

**Issue by hvtrieu1803** [magento/merchdocs#171] opened 2019-11-20 02:42 UTC
Hi Guys,
I'm using Magento 2.3.2 but I don't see Reward Point in the path Stores > Settings > Configuration > Customers > ....
Can you help me?
Thank all very much

**Comment by dobooth** [comment] 2019-11-21 19:23
Thanks for the report, @hvtrieu1803. Rewards Points is a feature in the Commerce edition. Is that the version you are using? Please ensure you are in the correct version of the docs as well. Please update this issue with any more details you might have.

**Comment by hickskenh** [comment] 2019-12-03 20:40
@hvtrieu1803 Did the above reply help you?  If you are not using the Commerce edition, the Reward Points feature isn't available.  If you are using the Open Source edition and viewing our online docs, make sure you click Commerce 2.3 in the header bar and select Open Source to view docs for Open Source.   Please update this issue with your feedback.  If the issue isn't updated by Monday, Dec 9, we'll close this issue.

**Comment by shrielenee** [comment] 2019-12-12 19:41
Hello @hvtrieu1803 --- 

Thank you for your feedback! It doesn't seem like your issue is related to Magento MerchDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
--

**Closed by shrielenee** 2019-12-12 19:41 UTC
Labels: Waiting for response
