### ISSUE TITLE
Link doesn't go to the right page

### ISSUE THREAD

**Issue by rostaylo** [magento/merchdocs#1724] opened 2022-04-21 20:22 UTC
# Bug report

## Description

The link in the documentation does not go to the right page, it is redirected to blog home page.

### Steps to reproduce

1. Click [Top ERP Packages that Integrate with Adobe Commerce](https://magento.com/blog/best-practices/top-erp-packages-integrate-magento).

## Expected result

User should be sent to blog post explaining the Top ERP Packages...

**Comment by hickskenh** [comment] 2022-04-21 20:30
This issue is due to the blog migration.  the migration team did not transfer all magento blogs. because the article no longer exists, it redirects to the new blog's home page.  will review and remove the link.

**Comment by hickskenh** [comment] 2022-04-21 20:31
@rostaylo please provide the web page you where you found the error.

**Comment by dobooth** [comment] 2022-04-28 18:40
Closing as dupe of https://github.com/magento/merchdocs/issues/1726 and will have a PR to fix this soon.

**Closed by dobooth** 2022-04-28 18:40 UTC
Labels: bug, Progress: on hold
