### ISSUE TITLE
Determine if you can have a different price at the store level

### ISSUE THREAD

**Issue by sparrowek** [magento/merchdocs#1424] opened 2021-08-06 14:09 UTC
Is this correct? Can I have a different price at the store level?

Look here
https://magento.stackexchange.com/questions/210203/different-prices-for-different-store-views

**Comment by ZhovnirMaria** [comment] 2021-08-19 11:46
@magento I am working on this

**Comment by hickskenh** [comment] 2022-04-22 16:17
@ZhovnirMaria please advise if you still are working on this ticket or should it be assigned to someone else?

**Comment by dshevtsov** [comment] 2024-09-03 15:53
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/catalog/products/pricing/catalog-price-scope.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.

**Closed by dshevtsov** 2024-09-03 15:53 UTC
Labels: Progress: ready for grooming, migrate
