### ISSUE TITLE
The search for "Adobe Stock Integration" doesn't find any result

### ISSUE THREAD

**Issue by chalov-anton** [magento/merchdocs#208] opened 2019-12-17 13:59 UTC
# Bug report

## Description
The search for "Adobe Stock Integration" doesn't find any result
### Steps to reproduce
In the main page of merchdocs click on :mag: **Search**  and type "_Adobe Stock Integration_"
## Expected result
The propper topic is found
## Actual Result
No results found
![search](https://user-images.githubusercontent.com/45624059/71001500-15e33480-20e6-11ea-93ca-5ce44f985af9.png)

**Comment by shrielenee** [comment] 2020-01-09 19:51
This is actually expected behavior, as this product has not yet been released. Stay tuned :)

**Comment by shrielenee** [comment] 2020-01-09 19:52
Actually... upon further inspection there may be a TOC-related error. We will investigate. @leslietilling

**Comment by konarshankar07** [comment] 2020-02-22 09:28
I'm also not able to reproduce this issue. Please close the ticket if you are also not able to reproduce this issue
Thanks

**Comment by leslietilling** [comment] 2020-03-04 16:24
Yes this content was not yet merged and part of production until the January 2.3.4 release. It is "as designed" that it was not part of the indexing that powers our search functionality. 

Closing this issue.

**Closed by leslietilling** 2020-03-04 16:24 UTC
Labels: Progress: ready for dev, groomed
